version: '3.9'

networks:
    my-network:

volumes: 
    mysql-data:

services:
    web:
        build: .
        container_name: my-python-app
        hostname: my-app
        ports:
            - 8080:5000
        networks: 
            my-network:
        volumes:
            - .:/code
        environment:
            FLASK_ENV: development
    redis:
        image: redis:alpine
        container_name: my-redis-db
        hostname: my-redis-db
        ports:
            - 6379:6379
        networks:
            my-network:
    mysql:
        image: mysql/mysql-server
        container_name: my-mysql-db
        hostname: my-mysql-db
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: MY_DB_USER
            MYSQL_DATABASE: MY_DB
            MYSQL_PASSWORD: MY_DB_PW
        volumes:
            - mysql-data:/var/lib/mysql
        ports:
            - 3306:3306
        networks:
            my-network: